apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j-db
spec:
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - name: neo4j
        image: neo4j:5.11.0
        env:
        - name: NEO4J_AUTH
          value: "neo4j/password123"
        # --- 关键补丁：防止 K8s 环境变量冲突 ---
        - name: NEO4J_server_config_strict__validation_enabled
          value: "false"
        # -----------------------------------
        ports:
        - containerPort: 7474
        - containerPort: 7687
        volumeMounts:
        - mountPath: "/data"
          name: neo4j-data
        # 探针：给它点启动时间，别急着杀它
        startupProbe:
          tcpSocket:
            port: 7474
          failureThreshold: 30
          periodSeconds: 10
      volumes:
      - name: neo4j-data
        persistentVolumeClaim:
          claimName: neo4j-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
spec:
  selector:
    app: neo4j
  type: NodePort
  ports:
    - protocol: TCP
      port: 7687
      targetPort: 7687
      name: bolt
      nodePort: 30687  # <---【指定数据端口为 30687
    - protocol: TCP
      port: 7474
      targetPort: 7474
      name: http
      nodePort: 30074  # 这是之前的网页端口
