# --- Spark Master ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
spec:
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        # ---  使用我们要自己构建的镜像 ---
        image: spark-etl:v1
        # ---  强制使用本地镜像，不去网上拉 ---
        imagePullPolicy: Never
        command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
        ports:
        - containerPort: 7077
        - containerPort: 8080
        resources:
          limits:
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-service
spec:
  selector:
    app: spark-master
  ports:
  - port: 7077
    name: master
  - port: 8080
    name: webui
---
# --- Spark Worker ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
      - name: spark-worker
        # ---  Worker 也要用这个带依赖的镜像 ---
        image: spark-etl:v1
        # ---  强制本地 ---
        imagePullPolicy: Never
        command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master-service:7077"]
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
