# --- 1. API 服务 (生产者) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lineage-backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: api
        image: lineage-backend:v3  # 使用新镜像
        imagePullPolicy: Never
        command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lineage-backend-service
spec:
  type: NodePort
  selector:
    app: backend-api
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080

---
# --- 2. Worker 服务 (消费者) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lineage-backend-worker
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: backend-worker
  template:
    metadata:
      labels:
        app: backend-worker
    spec:
      containers:
      - name: worker
        image: lineage-backend:v3 # 使用同一个镜像
        imagePullPolicy: Never
        command: ["rq", "worker", "--url", "redis://redis-service:6379"]
        env:
        - name: NEO4J_URI
          value: "bolt://neo4j-service:7687"
