apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j-db
spec:
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - name: neo4j
        image: neo4j:5.11.0
        env:
        - name: NEO4J_AUTH
          value: "neo4j/password123"
        # 关闭严格校验，忽略 K8s 注入的冲突变量
        - name: NEO4J_server_config_strict__validation_enabled
          value: "false"
        # ------------------------
        ports:
        - containerPort: 7474
        - containerPort: 7687
        volumeMounts:
        - mountPath: "/data"
          name: neo4j-data
        # 探针配置，防止 K8s 还没等它启动完就认为它挂了
        startupProbe:
          tcpSocket:
            port: 7687
          failureThreshold: 30
          periodSeconds: 10
      volumes:
      - name: neo4j-data
        persistentVolumeClaim:
          claimName: neo4j-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
spec:
  selector:
    app: neo4j
  ports:
    - protocol: TCP
      port: 7687
      targetPort: 7687
      name: bolt
    - protocol: TCP
      port: 7474
      targetPort: 7474
      name: http
