apiVersion: apps/v1
kind: Deployment
metadata:
  name: lineage-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: nginx
        image: lineage-ui:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lineage-ui-service
spec:
  type: NodePort
  selector:
    app: ui
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081 # 固定对外端口 30081
