apiVersion: v1
kind: Pod
metadata:
  name: spark-submit-job
spec:
  containers:
  - name: spark-submit
    image: spark-etl:v1
    imagePullPolicy: Never
    env:
    # 获取 Pod 自身的 IP
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    command:
    - /opt/spark/bin/spark-submit
    - --master
    - spark://spark-master-service:7077
    - --deploy-mode
    - client
    # 强制告诉 Spark：别用主机名，用这个 IP 地址！
    - --conf
    - spark.driver.host=$(MY_POD_IP)
    - --conf
    - spark.driver.bindAddress=0.0.0.0
    # -------------------
    - --conf
    - spark.executor.memory=512m
    - --conf
    - spark.driver.memory=512m
    - /app/etl_job.py
  restartPolicy: Never
