apiVersion: v1
kind: Pod
metadata:
  name: spark-submit-job
spec:
  containers:
  - name: spark-submit
    image: spark-etl:v1
    imagePullPolicy: Never
    # 核心命令：spark-submit 指向我们的 Master
    command:
    - /opt/spark/bin/spark-submit
    - --master
    - spark://spark-master-service:7077
    - /app/etl_job.py
  restartPolicy: Never
